#!/bin/sh
csv=$1
matlab -nodesktop -nosplash <<EOF
clear;
brpath_i = which('InitBreach');
while ~isempty(brpath_i)
	brpath = replace(brpath_i, 'InitBreach.m','');
	rmpath(brpath);
	brpath_i = which('InitBreach');
end
addpath(genpath('.'));
addpath(genpath('/home/zhenya/breach/'));
InitBreach;

warning('off', 'f16:no_analysis'); 

%% Breach interface setup
sg = f16_signal_gen();
B = BreachSignalGen(sg);
tspan = 0:.01:15;
B.SetTime(tspan);

input_name = {'phig', 'thetag', 'psig'};
input_range = [[pi/4-pi/20 pi/4+pi/30];[-0.8*pi/2 -pi/2*0.8+pi/20];[-pi/4-pi/8 -pi/4+pi/8]];

B.SetParamRanges( {'phig', 'thetag', 'psig'}, [ pi/4-pi/20 pi/4+pi/30;...
    -0.8*pi/2, -pi/2*0.8+pi/20; ...
    -pi/4-pi/8 -pi/4+pi/8]);

spec = 'alw (altitude[t]>0)';
phi = STL_Formula('phi', spec);

mdl = 'F16';
budget = 2000;
solver = 'cmaes';
algorithm = 'breach';
specID = 'F1';

filename = strcat(mdl, '_', algorithm, '_', specID, '_', int2str(budget), '_', solver);

trials = 30;
min_rob = [];
coverage = [];
time_cov = [];
for n = 1:trials
	logname = strcat('test/log/', filename, '_', int2str(n));
	log = breachSampling(B, budget, phi, controlpoints, tspan, input_name, input_range, solver);
	save(logname, 'log');
end
quit
EOF
