#!/bin/sh
csv=$1
/home/zhenya/temp/bin/matlab -nodesktop -nosplash <<EOF
clear;
addpath(genpath('/home/zhenya/git/coverage-confidence/'));
addpath(genpath('/home/zhenya/tools/breach/'));
InitBreach;
 
warning('off', 'f16:no_analysis'); 

%% Breach interface setup
sg = f16_signal_gen();
B = BreachSignalGen(sg);
tspan = 0:.01:15;
B.SetTime(tspan);
input_name = {'phig', 'thetag', 'psig'};
input_range = [[pi/4-pi/20 pi/4+pi/30];[-0.8*pi/2, -pi/2*0.8+pi/20];[-pi/4-pi/8 -pi/4+pi/8]];
B.SetParamRanges( input_name, input_range);

spec = 'alw_[0,15](altitude[t]>0)';
phi = STL_Formula('phi',spec);

budget = 500;

mdl = 'F16';
specID = 'F1';
algorithm = 'random';
filename = strcat(mdl, '_', algorithm, '_', specID, int2str(budget));

trials = 5;
min_rob = [];
coverage = [];
time_cov =[];
for n = 1:trials
	logname = strcat('test/log/', filename, '_', int2str(n));
	log = paramRandomSample(B, budget, phi, tspan, input_name, input_range);
	save(logname, 'log');
end
quit
EOF
